spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true

server:
  port: 8085
